import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head></head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased body`}
      >
        {children}
        {/* Webflow HTML flags (w-mod-js / w-mod-touch) */}
        <Script id="webflow-flags" strategy="beforeInteractive">{`
          (function(o,c){var n=c.documentElement,t=" w-mod-";n.className+=t+"js"; ("ontouchstart" in o || (o.DocumentTouch && c instanceof o.DocumentTouch)) && (n.className+=t+"touch");})(window,document);
        `}</Script>
        {/* Google WebFont loader for Montserrat and Inconsolata to match Webflow typography */}
        <Script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" strategy="afterInteractive" />
        <Script id="load-webfonts" strategy="afterInteractive">{`
          try { WebFont.load({ google: { families: ["Montserrat:100,200,300,400,500,600,700,800,900","Inconsolata:400,700"] } }); } catch(e){}
        `}</Script>
        <Script type="module" src="/js/index.js" strategy="afterInteractive" />
        <Script type="module" src="/js/filters.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
